### ISSUE TITLE
Comparison of negative numbers fails

### ISSUE THREAD

**Issue by vanboom** [nwoltman/string-natural-compare#15]
Reference:  https://github.com/javve/list.js/issues/562#issuecomment-2392500110

**Comment by nwoltman** [comment]
Hi @vanboom. I've addressed this issue before here: https://github.com/nwoltman/string-natural-compare/issues/1#issuecomment-316835327

Treating numbers with a `-` sign before them as negative numbers is generally not a feature of natural sorting algorithms and I have no plans to include handling for negative numbers in this module (same goes for numbers with decimals). Implementing those features would require introducing heuristics which would work for some people, but break sorting for other people.

My recommendation is to handle sorting strings that are pure numbers separately, and then pass other strings to string-natural-compare.
