### ISSUE TITLE
Differences from alphanum?

### ISSUE THREAD

**Issue by TehShrike** [nwoltman/string-natural-compare#6]
I found this package by searching npm for "alphanum", which is one of this module's keywords: https://github.com/nwoltman/string-natural-compare/blob/3e0a51624ed49f2a4069e8fb13f9052a2165707d/package.json#L24

Are there any differences between this package's algorithm and the [Alphanum algorithm](http://davekoelle.com/alphanum.html)?  If so, what are they?

**Comment by nwoltman** [comment]
Nope, I don't think there are any differences. I tried sorting the lists of strings from that article using this package and got the same results as the article.

**Comment by TehShrike** [comment]
👍 Cool, good to know.  Might be worth noting that in the readme – "alphanum algorithm" is the thing I know to search for when I want natural string sorting.
